apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: 'false'
    containerImage: null
    createdAt: '2019-04-10T12:35:53Z'
    description: OpenShift cluster provisioning and management at scale.
    support: OSD SRE
  containerImage: quay.io/openshift-sre/dedicated-admin-operator:v0.1.71-2019-04-10-966895f1
  name: dedicated-admin-operator.v0.1.71-2019-04-10-966895f1
  namespace: openshift-dedicated-admin
spec:
  description: SRE operator - dedicated-admin-operator
  displayName: dedicated-admin-operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - rbac.authorization.k8s.io
          attributeRestrictions: null
          resources:
          - clusterrolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ''
          - oauth.openshift.io
          attributeRestrictions: null
          resources:
          - oauthclientauthorizations
          verbs:
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - authorization.openshift.io
          attributeRestrictions: null
          resources:
          - resourceaccessreviews
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          attributeRestrictions: null
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - ''
          - project.openshift.io
          attributeRestrictions: null
          resources:
          - projectrequests
          verbs:
          - create
        - apiGroups:
          - ''
          attributeRestrictions: null
          resources:
          - nodes
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - security.openshift.io
          attributeRestrictions: null
          resources:
          - securitycontextconstraints
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - quota.openshift.io
          attributeRestrictions: null
          resources:
          - clusterresourcequotas
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - authorization.openshift.io
          attributeRestrictions: null
          resources:
          - clusterpolicybindings
          verbs:
          - get
          - list
        - apiGroups:
          - ''
          - network.openshift.io
          attributeRestrictions: null
          resources:
          - netnamespaces
          verbs:
          - get
          - list
          - update
        serviceAccountName: dedicated-admin-operator
      - rules:
        - apiGroups:
          - ''
          attributeRestrictions: null
          resources:
          - limitranges
          - resourcequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ''
          - network.openshift.io
          attributeRestrictions: null
          resources:
          - egressnetworkpolicies
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - extensions
          attributeRestrictions: null
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          attributeRestrictions: null
          resources:
          - clusterrolebindings
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ''
          attributeRestrictions: null
          resources:
          - events
          - namespaces
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - network.openshift.io
          attributeRestrictions: null
          resources:
          - clusternetworks
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - image.openshift.io
          attributeRestrictions: null
          resources:
          - images
          - imagestreamtags
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ''
          - build.openshift.io
          attributeRestrictions: null
          resources:
          - buildconfigs
          - builds
          verbs:
          - get
          - list
          - watch
        serviceAccountName: dedicated-admin-operator
      deployments:
      - name: dedicated-admin-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              k8s-app: dedicated-admin-operator
          template:
            metadata:
              labels:
                k8s-app: dedicated-admin-operator
            spec:
              containers:
              - command:
                - dedicated-admin-operator
                env:
                - name: WATCH_NAMESPACE
                  value: ''
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: dedicated-admin-operator
                image: quay.io/openshift-sre/dedicated-admin-operator:v0.1.71-2019-04-10-966895f1
                imagePullPolicy: Always
                name: dedicated-admin-operator
                ports:
                - containerPort: 60000
                  name: metrics
              serviceAccountName: dedicated-admin-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  maturity: alpha
  provider:
    name: Red Hat, Inc
  replaces: dedicated-admin-operator.v0.1.31-2019-03-29-3ff1db8
  version: 0.1.71-2019-04-10-966895f1
